backend:
  name: github
  repo: Pichok/blog-2

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    folder: src/pages/articles
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: layout, label: Layout }
      - { name: draft, label: Draft, widget: boolean }
      - { name: path, label: Path }
      - { name: category, label: Category, widget: select, options: ["Design", "UX", "Dev"] }
      - { name: tags, label: Tags, widget: select, multiple: true, options: ["Design", "UX", "Dev"] }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
