backend:
  name: github
  repo: Pichok/blog-2

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    folder: src/pages/articles
    create: true
    fields:
      - { name: title, label: Title }
